#!/bin/bash

ALPINE_SETUP()
{
  echo "" | $SUDO tee /etc/motd
  $SUDO setup-xorg-base

  echo '#!/bin/sh

  echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor' | $SUDO tee /etc/local.d/cpufreq.start
  $SUDO chmod +x /etc/local.d/cpufreq.start

  $SUDO adduser $USER input
  $SUDO apk -U upgrade
  $SUDO apk add lsblk make musl-dev ncurses xorg-server-common xorg-server-dev xproto xorgxrdp xorgxrdp-dev setxkbmap zzz ttf-dejavu \
    mesa-dri-gallium libva-intel-driver alsa-utils alsa-utils-doc alsa-lib alsaconf alsa-ucm-conf pulseaudio pulseaudio-alsa alsa-plugins-pulse \
    util-linux elogind polkit-elogind qemu-img qemu-ui-sdl qemu-hw-display-virtio-vga-gl libvirt-qemu qemu-hw-display-virtio-vga coreutils iwd networkmanager-wifi

  for n in dbus alsa elogind; do
    $SUDO rc-update add $n
  done

  $SUDO rc-update add local default
  $SUDO rc-update del wpa_supplicant boot
  $SUDO rc-update add iwd boot
  $SUDO rc-update add sshd
  $SUDO rc-update add networkmanager boot
  $SUDO sed -i 's/#rc_parallel=\"NO\"/rc_parallel=\"YES\"/g' /etc/rc.conf
  $SUDO sed -i 's/root:\/bin\/ash/root:\/sbin\/nologin/g' /etc/passwd
  $SUDO sed -i "s/sbin\/getty 38400 tty1/bin\/login -f $USER/g" /etc/inittab

  $SUDO rm -r /media/{cdrom,usb}

  $SUDO mkdir /etc/udhcpc
  echo 'RESOLV_CONF="no"' | $SUDO tee /etc/udhcpc/udhcpc.conf

  echo "nameserver 1.1.1.1
  nameserver 8.8.8.8" | $SUDO tee /etc/resolv.conf

  $SUDO tee -a /etc/NetworkManager/NetworkManager.conf << EOF
dns=none

[ifupdown]
managed=true

[device]
wifi.backend=iwd
EOF

  for n in plugdev qemu kvm libvirt; do
    $SUDO adduser $USER $n
  done
}
