#!/bin/bash

ARCH_SETUP()
{
  echo "Defaults:$USER timestamp_timeout=60" | $SUDOAS tee /etc/sudoers.d/$USER
  $PKGINSTALL --needed base-devel git

  if [ $RELEASE = Arch ]; then
    git clone https://aur.archlinux.org/trizen.git
    cd trizen || exit
    makepkg -si --noconfirm
    cd || exit
    $SUDOAS rm -R trizen
  fi

  $SUDOAS tee -a /etc/pacman.conf << EOF

[archzfs]
Include = /etc/pacman.d/mirrorlist-archzfs
EOF

  curl -L https://git.io/Jsfw2 | $SUDOAS tee /etc/pacman.d/mirrorlist-archzfs
  curl -L https://archzfs.com/archzfs.gpg | $SUDOAS pacman-key -a -
  $SUDOAS pacman-key --lsign-key "$(curl -L https://git.io/JsfVS)"

  $SUDOAS pacman --noconfirm -Syu
  $PKGINSTALL linux-lts-headers zfs-dkms zfs-utils
}
