#!/bin/bash

NIXOS_SETUP()
{
  mkdir .config
  curl -L https://raw.githubusercontent.com/sorathpanzer/nixos/main/configuration.nix > configuration.nix
  $SUDO sed "s/hostId =.*/hostId = \""$(head -c 8 /etc/machine-id)"\"/g" /etc/nixos/configuration.nix

  if [ ! -f "/crypto_keyfile.bin" ]; then
    $SUDO sed -i '/initrd.secrets /s//#initrd.secrets/' configuration.nix
  fi

  $SUDO cp configuration.nix /etc/nixos/configuration.nix
  $SUDO nixos-rebuild switch
  nmcli con mod Virus404 ipv4.dns "1.1.1.2 1.0.0.2"
  $SUDO systemctl restart NetworkManager
}
