#!/bin/bash

VOID_SETUP()
{
  echo "Defaults:$USER timestamp_timeout=60" | $SUDO tee /etc/sudoers.d/$USER
  $SUDO xbps-install -Syu
  $SUDO xbps-install -Sy make pkg-config snapper setxkbmap pulseaudio xdg-utils opendoas

  $SUDO snapper -c root create-config /
  $SUDO btrfs subvolume delete /.snapshots
  $SUDO mkdir /.snapshots
  $SUDO sed -i '/@snapshots/s/^#//' /etc/fstab

  echo "GETTY_ARGS=\"--autologin $USER --noclear\"
  BAUD_RATE=38400
  TERM_NAME=linux" | $SUDO tee /etc/sv/agetty-tty1/conf

  $SUDO ln -s /etc/sv/pipewire /var/service
  $SUDO ln -s /etc/sv/acpid /var/service
}
