#!/bin/bash

CONFIGURE_HOME()
{
  [ -e $HOME/.profile ] && rm $HOME/.profile
  mkdir -p $HOME/{Transferências,Documentos,Música,Imagens/Screenshots,Vídeos,.config,.cache/{lf,transmission}}
  mkdir -p $HOME/.local/share/{backgrounds,gvfs-metadata,icc,keyrings,nvim,sounds,Trash,xorg}
  touch $HOME/.local/recently-used.xbel
  git config --global user.name "$GIT_USERNAME"
  git config --global user.email "$GIT_EMAIL"
  echo "Cloning my dotfiles..."
  git clone --progress $DOTFILES $HOME/.config/dotgit
  git config --global credential.helper store
  mkdir -p $HOME/.cache/zsh
  touch $HOME/.cache/zsh/history
  sh -c "cd /home/$USER/.config/dotgit; stow -vt ~ dotfiles"

  if [ -n "$LVM_PASSWORD" ]; then
    echo "Open vault password:"
    $SUDO modprobe zfs
    echo -n "$LVM_PASSWORD" | $SUDO zpool import -lf -R /media Legion
    rsync -avrop /media/Legion/Crypta/BackHome/ /home/$USER
  else
    rsync -av --info=progress2 root@192.168.1.104:/mnt/Bunker/Vault/BackHome/ /home/$USER
  fi

  if [ $RELEASE = Void ] || [ $RELEASE = Alpine ] || [ $RELEASE = FreeBSD ]; then
    $SUDO mkdir -p /usr/share/edk2/ovmf
    $SUDO cp .config/suckless/ovmf/OVMF_CODE.fd /usr/share/edk2/ovmf
  fi

  if [ -n "$($SUDO dmesg | grep Hypervisor)" ]; then
    hyprconf="$HOME/.config/hypr/hyprland.conf"
    [ -e $hyprconf ] && sed -i s/SUPER/ALT/ $hyprconf
  fi
}
