#!/bin/bash

echo "Hit ctrl-c when promted for which disk you'd like to use!"
setup-alpine
apk add zfs sfdisk e2fsprogs syslinux
echo -e "/dev/nvme0n1p1: start=1M,size=100M,bootable\n/dev/nvme0n1p2: start=101M" | sfdisk --quiet --label dos /dev/nvme0n1
mdev -s
mkfs.ext4 /dev/nvme0n1p1

modprobe zfs
  zpool create -f -o ashift=12 \
      -O acltype=posixacl -O canmount=off -O compression=lz4 \
      -O dnodesize=auto -O normalization=formD -O relatime=on -O xattr=sa \
      -O encryption=aes-256-gcm -O keylocation=prompt -O keyformat=passphrase \
      -O mountpoint=/ -R /mnt \
      rpool /dev/nvme0n1p2

zfs create -o mountpoint=none -o canmount=off rpool/ROOT
zfs create -o mountpoint=legacy rpool/ROOT/alpine
mount -t zfs rpool/ROOT/alpine /mnt/

mkdir /mnt/boot/
mount -t ext4 /dev/nvme0n1p1 /mnt/boot/

rc-update add zfs-import sysinit
rc-update add zfs-mount sysinit

setup-disk /mnt
dd if=/usr/share/syslinux/mbr.bin of=/dev/nvme0n1
