#!/bin/bash

exec &> >(tee -a "install.log") 2>install.error

############################################
# Sudo for second drive mount?????
# snd_hda can't create folder for powersave
#Dejavu libexif dhcpcd5 ueberzug
## alacritty lazygit dust python-adblock
############################################

# FIRST INSTALL GIT WGET CURL SUDO

USER_NAME=""
LVM_PASSWORD=""
GIT_USERNAME=""
GIT_EMAIL=""

# For RHEL systems
sudo dnf install --nogpgcheck https://dl.fedoraproject.org/pub/epel/epel-release-latest-$(rpm -E %rhel).noarch.rpm
sudo dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm

#For Silverblue/Fedora systems
#sudo rpm-ostree install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
#sudo rpm-ostree install https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

sudo rpm-ostree upgrade
sudo rpm-ostree install audit btrfs-progs crontabs dbus-x11 dunst feh ffmpeg ffmpegthumbnailer firefox flatpak fontconfig-devel freetype-devel fzf \ 
gcc giflib-devel git i3lock ImageMagick imlib2-devel keepassxc kitty libexif-devel libX11-devel libXext-devel libXft libXft-devel libXinerama-devel \ 
libxshmfence-devel light lm_sensors man mpv neovim NetworkManager-tui ntfs-3g numlockx picom pipewire pulseaudio-utils python3-devel python3-pip \
python3-six python3-wheel qemu qutebrowser scrot stow syncthing tig tldr trash-cli udiskie unzip wireguard-tools xdotool xinput xorg-x11-server-Xorg \ 
xorg-x11-xinit xrandr xrdb xset youtube-dl zsh zsh-autosuggestions zsh-syntax-highlighting

sudo rpm-ostree override remove zezere-ignition ignition dbus-parsec

# TOOLBOX
#sudo rpm-ostree install gcc fontconfig-devel freetype-devel libXft-devel libX11-devel libXinerama-devel libexif-devel imlib2-devel giflib-devel \
#python3-devel python3-pip libXext-devel libxshmfence-devel python3-wheel python3-devel

#sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#sudo flatpak install io.gitlab.librewolf-community net.agalwood.Motrix org.keepassxc.KeePassXC org.libreoffice.LibreOffice org.signal.Signal org.telegram.desktop -y


#echo "Open vault password:"
#sudo mkdir /media/Vault
#echo -n "$LVM_PASSWORD" | cryptsetup open --type luks /dev/sda1 Vault
#mount /dev/mapper/Vault /media/Vault

rm $HOME/.profile
mkdir -p /home/$USER_NAME/{Transferências,Documentos,Música,Imagens/Screenshots,Vídeos,.cache/{lf,transmission}}
mkdir -p /home/$USER_NAME/.local/share/{backgrounds,gvfs-metadata,icc,keyrings,nvim,sounds,Trash,xorg}
touch /home/$USER_NAME/.local/recently-used.xbel
git config --global user.name "$GIT_USERNAME"
git config --global user.email "$GIT_EMAIL"
git clone https://gitea.com/sorathpanzer/dotgit.git /home/$USER_NAME/.config/dotgit
git config --global credential.helper store
mkdir -p /home/$USER_NAME/.cache/zsh
touch /home/$USER_NAME/.cache/zsh/history
sh -c "cd /home/$USER_NAME/.config/dotgit; stow -vt ~ dotfiles"
touch /home/$USER_NAME/.local/recently-used.xbel

#rsync -avrop /media/Vault/BackHome/* /home/$USER_NAME
#chmod +x /home/$USER_NAME/.local/bin/lf
#cd ~/.config/suckless/st
#make clean; make install clean
#cd

sudo mkdir -p /sys/module/snd_hda_intel/parameters/
sudo mkdir -p /etc/polkit-1/rules.d/
echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.d/99-sysctl.conf
echo 1 | sudo tee /sys/module/snd_hda_intel/parameters/power_save
echo "blacklist ideapad_laptop" | sudo tee /etc/modprobe.d/blacklist.conf

echo "[udiskie]
Identity=unix-group:plugdev
Action=org.freedesktop.udisks.*
ResultAny=yes" | sudo tee /etc/polkit-1/localauthority/50-local.d/consolekit.pkla

  echo '/* Allow members of the wheel group to execute any actions
  * without password authentication, similar to "sudo NOPASSWD:"
  */
  polkit.addRule(function(action, subject) {
  if (subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});' | sudo tee /etc/polkit-1/rules.d/49-nopasswd_global.rules
echo 'polkit.addRule(function(action, subject) {
if ((action.id == "org.freedesktop.udisks2.filesystem-mount-system" ||
  action.id == "org.freedesktop.udisks.filesystem-mount-system-internal") &&
  subject.local && subject.active && subject.isInGroup("wheel"))
  {
    return polkit.Result.YES;
  }
});' | sudo tee /etc/polkit-1/rules.d/allow-mount-internal.rules

sudo mkdir -p /media

echo '# UDISKS_FILESYSTEM_SHARED
# ==1: mount filesystem to a shared directory (/media/VolumeName)
# ==0: mount filesystem to a private directory (/run/media/$USER/VolumeName)
# See udisks(8)
ENV{ID_FS_USAGE}=="filesystem|other|crypto", ENV{UDISKS_FILESYSTEM_SHARED}="1"' | sudo tee /etc/udev/rules.d/99-udisks2.rules

sudo mkdir /etc/iwd

echo "[General]
EnableNetworkConfiguration=true
[Settings]
AutoConnect=true" | sudo tee /etc/iwd/main.conf

echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf

#sudo cp /usr/lib/systemd/system/getty@.service /etc/systemd/system/autologin@.service
#sudo sed -i 's/ExecStart=.*/ExecStart=-\/sbin\/agetty -a sorath --noclear %I $TERM/' /usr/lib/systemd/system/getty@.service

 echo "[Unit]
Description=Lock X session using slock for user %i
Before=sleep.target

[Service]
User=%i
Type=forking
Environment=DISPLAY=:0
ExecStartPre=/usr/bin/xset dpms force suspend
ExecStart=/usr/bin/i3lock -c 000000

[Install]
WantedBy=sleep.target" | sudo tee /etc/systemd/system/suspend@.service
 
echo "source /etc/network/interfaces.d/*
auto wlan0
iface wlan0 inet dhcp" | sudo tee /etc/network/interfaces 
 
sudo systemctl enable --now  iwd.service suspend@sorath.service firewalld

echo 'Section "InputClass"
        Identifier "libinput touchpad catchall"
        MatchIsTouchpad "on"
        MatchDevicePath "/dev/input/event*"
        Driver "libinput"
        Option "NaturalScrolling" "true"
EndSection' | sudo tee /etc/X11/xorg.conf.d/40-libinput.conf

#automated_script
sudo rfkill unblock all
sudo ip link set wlan0 up
iwctl station wlan0 scan
iwctl station wlan0 connect Virus404 -P $WIFIPASS

sudo cp $HOME/Documentos/wg0.conf /etc/wireguard

sudo usermod -a -G plugdev $USER
sudo usermod -s /usr/bin/zsh $USER

sudo mkdir -p /etc/systemd/system/getty@tty1.service.d/
sudo touch /etc/systemd/system/getty@tty1.service.d/override.conf
echo '[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin sorath --noclear %I $TERM' | sudo tee /etc/systemd/system/getty@tty1.service.d/override.conf

echo "Defaults:sorath !authenticate
sorath ALL=(ALL) NOPASSWD: /usr/bin/wg-quick, /usr/bin/ostree, /usr/sbin/reboot, /usr/sbin/poweroff" | sudo tee /etc/sudo.d/sorath

echo "sorath" | sudo tee -a /etc/shutdown.allow

cat install.error | grep error
