#!/usr/bin/env bash

# Version= 0.5.6

# TODO: Before running this script you must install:
# FreeBSD -> doas, bash >>>>>>>> "permit nopass keepenv $USER as root" to doas.conf
# OpenBSD|Alpine -> bash

exec 1> >(tee "install.log") 2> >(tee "install.error")

LVM_PASSWORD=""
GIT_USERNAME="${USER}panzer"
GIT_EMAIL="$GIT_USERNAME"
DOTFILES="https://gitea.com/sorathpanzer/dotgit.git"
WM="Hyprland"
SUDO="sudo"
RELEASE=$(grep ^NAME= /etc/os-release | cut -d '=' -f2 | awk '{print $1}' | tr -d '"')
UPPERCASE=$(echo $RELEASE | tr '[:lower:]' '[:upper:]')

source_files() {
    local dir="$1"

    if [[ -d "$dir" && -r "$dir" && -x "$dir" ]]; then
        for file in "$dir"/*; do
           [[ -f "$file" && -r "$file" ]] && . "$file"
        done
    fi
}

source_files Distros
source_files Modules
source_files Wm

CONFIGURE_PACKAGES

case "${RELEASE}" in
  FreeBSD|OpenBSD)
    INSTALL_PACKAGES
    CONFIGURE_HOME
    ${UPPERCASE}_SETUP ;;
  NixOS)
    CONFIGURE_HOME
    NIXOS_SETUP ;;
  *)
    ${UPPERCASE}_SETUP
    INSTALL_PACKAGES
    CONFIGURE_HOME
    CONFIGURE_SYSTEM ;;
esac

grep error install.error
