#!/bin/bash

  sudo tee -a /etc/pacman.conf << EOF

[archzfs]
Include = /etc/pacman.d/mirrorlist-archzfs
EOF

  curl -L https://git.io/Jsfw2 | sudo tee /etc/pacman.d/mirrorlist-archzfs
  curl -L https://archzfs.com/archzfs.gpg | sudo pacman-key -a -
  sudo pacman-key --lsign-key "$(curl -L https://git.io/JsfVS)"
  #sudo pacman-key -r DDF7DB817396A49B2A2723F7403BD972F75D9D76
  #sudo pacman-key --lsign-key DDF7DB817396A49B2A2723F7403BD972F75D9D76

  #sudo pacman -Syu
  #sudo pacman -S linux-lts-headers zfs-dkms zfs-utils
