#!/bin/bash

HYPR_PACKAGES()
{
  SWWW=(          "$NA"                     swww                  swww                    swww                swww                swww                swww                swww                        swww                  swww                )

  $PKGINSTALL foot caja waybar ydotool tofi alacritty wl-clipboard grim slurp libnotify-bin ${SWWW}

  if [ -n "$($SUDO dmesg | grep Hypervisor)" ]; then
    sed -i s/SUPER/ALT/ $HOME/.config/hypr/hyprland.conf
  fi
}
