#!/bin/bash

if [ $WM = Hyprland ]; then
  SWWW=(          "$NA"                     swww                  swww                    swww                swww                swww                swww                swww                        swww                  swww                )

  $PKGINSTALL foot caja waybar ydotool tofi alacritty wl-clipboard grim slurp libnotify-bin ${SWWW}
fi

