#!/bin/bash

  NA=" "
  # DISTRO=(      Debian/Devuan             Fedora                AlmaLinux/Rocky/CentOS  Arch                Artix               Void                Alpine              OpenSuse                    FreeBSD               OpenBSD             )
  #---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------)
  ADBLOCK=(       "$NA"                     "$NA"                 "$NA"                   python-adblock      python-adblock      python3-adblock     py3-adblock         "$NA"                       py39-adblock          py3-adblock         )
  ANDROIDTOOLS=(  android-tools-adb         android-tools         "$NA"                   android-tools       "$NA"               android-tools       android-tools       "$NA"                       android-tools         "$NA"               )
  BTRFSPROGS=(    btrfs-progs               btrfs-progs           "$NA"                   btrfs-progs         btrfs-progs         btrfs-progs         btrfs-progs         btrfsprogs                  "$NA"                 "$NA"               )
  CRONTABS=(      python3-crontab           crontabs              crontabs                "$NA"               "$NA"               "$NA"               "$NA"               python3-crontab             py39-python-crontab   "$NA"               )
  DOAS=(          "$NA"                     "$NA"                 "$NA"                   "$NA"               "$NA"               "$NA"               doas                "$NA"                       doas                  "$NA"               )
  EMACSNX=(       emacs-nox                 emacs-nox             emacs-nox               emacs-nox           emacs-nox           emacs               emacs-nox           emacs-nox                   emacs-nox             emacs-nosx          )
  FFTHUMBNAILER=( ffmpegthumbnailer         ffmpegthumbnailer     "$NA"                   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer           ffmpegthumbnailer     ffmpegthumbnailer   )
  FIREFOX=(       firefox-esr               firefox               firefox                 firefox             firefox             firefox             firefox             MozillaFirefox              firefox-esr           firefox-esr         )
  FLATPAK=(       flatpak                   "$NA"                 flatpak                 flatpak             flatpak             flatpak             flatpak             flatpak                     "$NA"                 "$NA"               )
  FZF=(           fzf                       fzf                   "$NA"                   fzf                 fzf                 fzf                 fzf                 fzf                         fzf                   fzf                 )
  GCC=(           gcc                       "$NA"                 gcc                     gcc                 gcc                 "$NA"               gcc                 gcc                         gcc                   gcc%11              )
  GIT=(           git                       "$NA"                 git                     git                 git                 git                 git                 git                         git                   git                 )
  IMAGEMAGICK=(   imagemagick               ImageMagick           ImageMagick             imagemagick         imagemagick         ImageMagick         imagemagick         ImageMagick                 ImageMagick7-nox11    ImageMagick         )
  LF=(            "$NA"                     "$NA"                 "$NA"                   lf                  "$NA"               lf                  lf                  "$NA"                       lf                    lf                  )
  LIBREOFFICE=(   libreoffice-calc          libreoffice-calc      libreoffice-calc        libreoffice-still   "$NA"               libreoffice-calc    "$NA"               libreoffice-calc            libreoffice           libreoffice         )
  LIGHT=(         light                     light                 "$NA"                   light               "$NA"               light               light               "$NA"                       "$NA"                 "$NA"               )
  LMSENSORS=(     lm-sensors                lm_sensors            lm_sensors              lm_sensors          lm_sensors          lm_sensors          lm-sensors          sensors                     "$NA"                 "$NA"               )
  NFSUTILS=(      nfs-common                nfs-utils             nfs-utils               nfs-utils           nfs-utils           nfs-utils           nfs-utils           nfs-utils                   "$NA"                 "$NA"               )
  NMTUI=(         "$NA"                     NetworkManager-tui    NetworkManager-tui      "$NA"               "$NA"               "$NA"               networkmanager-tui  "$NA"                       "$NA"                 networkmanager-tui  )
  NTFS3G=(        ntfs-3g                   ntfs-3g               ntfs-3g                 ntfs-3g             ntfs-3g             ntfs-3g             ntfs-3g             ntfs-3g                     fusefs-ntfs           ntfs_3g             )
  OPENSSH=(       openssh-client            "$NA"                 openssh                 openssh             openssh             openssh             openssh             openssh                     "$NA"                 "$NA"               )
  OVMF=(          ovmf                      edk2-ovmf             edk2-ovmf               edk2-ovmf           edk2-ovmf           "$NA"               ovmf                ovmf                        "$NA"                 "$NA"               )
  PANDOCPDF=(     pandoc                    pandoc-pdf            pandoc-pdf              pandoc              pandoc              pandoc              "$NA"               pandoc                      "$NA"                 pandoc              )
  POPPLERUTILS=(  poppler-utils             poppler-utils         poppler                 poppler             poppler             poppler-utils       poppler-utils       poppler-tools               poppler-utils         poppler-utils       )
  PAUTILS=(       pulseaudio-utils          pulseaudio-utils      pulseaudio-utils        "$NA"               "$NA"               pulseaudio-utils    pulseaudio-utils    pulseaudio-utils            "$NA"                 pulseaudio          )
  PYTHON=(        "$NA"                     python3-devel         python3-devel           "$NA"               "$NA"               python3-devel       python3-dev         python3-devel               python311             python3             )
  QEMU=(          qemu-system               "$NA"                 qemu-img                qemu-base           qemu-base           qemu                qemu-system-x86_64  qemu                        qemu                  qemu                )
  QUTEBROWSER=(   qutebrowser               qutebrowser           "$NA"                   qutebrowser         qutebrowser         qutebrowser         qutebrowser         qutebrowser                 qutebrowser           qutebrowser         )
  STOW=(          stow                      "$NA"                 stow                    stow                "$NA"               stow                stow                stow                        stow                  stow                )
  TELEGRAM=(      telegram-desktop          telegram-desktop      "$NA"                   telegram-desktop    "$NA"               telegram-desktop    telegram-desktop    telegram-desktop            telegram-desktop      "$NA"               )
  TIG=(           tig                       tig                   tig                     tig                 "$NA"               tig                 tig                 "$NA"                       tig                   tig                 )
  TRASHCLI=(      trash-cli                 trash-cli             "$NA"                   trash-cli           "$NA"               trash-cli           trash-cli           "$NA"                       "$NA"                 "$NA"               )
  UDISKIE=(       udiskie                   udiskie               "$NA"                   udiskie             udiskie             udiskie             udiskie             udiskie                     "$NA"                 "$NA"               )
  XF86INTEL=(     xserver-xorg-video-intel  xorg-x11-drv-intel    "$NA"                   xf86-video-intel    xf86-video-intel    xf86-video-intel    xf86-video-intel    xf86-video-intel            xf86-video-intel      "$NA"               )
  YOUTUBEDL=(     yt-dlp                    youtube-dl            youtube-dl              youtube-dl          youtube-dl          youtube-dl          youtube-dl          youtube-dl                  youtube_dl            youtube-dl          )
  ZATHURA=(       zathura                   zathura               zathura                 zathura             zathura             zathura             zathura             zathura                     zathura               zathura             )
  ZATHURAPDF=(    zathura-pdf-poppler       zathura-pdf-poppler   zathura-pdf-poppler     zathura-pdf-poppler "$NA"               zathura-pdf-poppler zathura-pdf-poppler zathura-plugin-pdf-poppler  zathura-pdf-poppler   zathura-pdf-poppler )
  ZFS=(           zfsutils-linux            "$NA"                 "$NA"                   "zfs-utils"         "$NA"               zfs                 zfs                 "$NA"                       "$NA"                 "$NA"               )

CONFIGURE_PACKAGES()
{
  case "${RELEASE}" in
    "")                  echo "$RELEASE is not supported!"; exit 1 ;;
    Debian|Devuan)	        POS="0"
      MK="tux"
      PKGINSTALL="$SUDO apt-get -y install" ;;
    Fedora)                 POS="1"
      MK="tux"
      PKGINSTALL="$SUDO rpm-ostree install" ;;
    AlmaLinux|Rocky|CentOS) POS="2"
      MK="tux"
      PKGINSTALL="$SUDO dnf install -y" ;;
    Arch)                   POS="3"
      MK="tux"
      PKGINSTALL="$SUDO pacman --noconfirm -S" ;;
    Artix)                  POS="4"
      MK="tux"
      PKGINSTALL="$SUDO pacman --noconfirm -S" ;;
    Void)                   POS="5"
      MK="tux"
      PKGINSTALL="$SUDO xbps-install -Sy" ;;
    Alpine)                 POS="6"
      MK="tux"
      PKGINSTALL="doas apk add" ;;
    openSUSE)               POS="7"
      MK="tux"
      PKGINSTALL="$SUDO zypper install -y" ;;
    FreeBSD)                POS="8"
      MK="bsd"
      PKGINSTALL="doas pkg install -y" ;;
    OpenBSD)                POS="9"
      MK="bsd"
      PKGINSTALL="doas pkg_add -i" ;;
    NixOS)  MK="nixos" ;;
  esac

  if [ $RELEASE = Alpine ]; then
    mkdir -p /etc/doas.d
    DOASCONF="/etc/doas.d/doas.conf"
  else
    DOASCONF="/etc/doas.conf"
  fi

  if [ $RELEASE = Void ] || [ $RELEASE = Alpine ] || [ $RELEASE = FreeBSD ] || [ $RELEASE = OpenBSD ]; then
    $SUDO tee $DOASCONF << EOF
permit persist $USER as root
permit nopass $USER cmd reboot
permit nopass $USER cmd poweroff
permit nopass $USER cmd mount
permit nopass $USER cmd setleds
permit nopass $USER cmd zfs
permit nopass $USER cmd zpool
EOF
  fi

  if [ $RELEASE = NixOS ]; then
    $SUDO sed -i 's/#  vim/git/' /etc/nixos/configuration.nix
    $SUDO sed -i 's/#  wget/stow zfs/' /etc/nixos/configuration.nix

    $SUDO sed -i '$d' /etc/nixos/configuration.nix
    $SUDO tee -a /etc/nixos/configuration.nix << EOF
security.sudo.configFile = ''
  Defaults:$USER timestamp_timeout=60
'';
}
EOF

    $SUDO nixos-rebuild switch
  fi
}

INSTALL_PACKAGES()
{
  $PKGINSTALL $HYPRLAND bzip2 ffmpeg groff keepassxc neovim mpv pipewire rsync sanoid syncthing unzip usbutils w3m wireguard-tools xdg-user-dirs zsh ripgrep \
    ${ADBLOCK[$POS]} ${ANDROIDTOOLS[$POS]} ${BTRFSPROGS[$POS]} ${CRONTABS[$POS]} ${FFTHUMBNAILER[$POS]} ${FIREFOX[$POS]} ${DOAS[$POS]} \
    ${FLATPAK[$POS]} ${FZF[$POS]} ${IMAGEMAGICK[$POS]} ${LIBREOFFICE[$POS]} ${LF[$POS]} ${NFSUTILS[$POS]} ${OPENSSH[$POS]} ${UDISKIE[$POS]} \
    ${LIGHT[$POS]} ${LMSENSORS[$POS]} ${NTFS3G[$POS]} ${PANDOCPDF[$POS]} ${POPPLERUTILS[$POS]} ${GIT[$POS]} ${XF86INTEL[$POS]} \
    ${PAUTILS[$POS]} ${PYTHON[$POS]} ${QEMU[$POS]} ${STOW[$POS]} ${TIG[$POS]} ${TRASHCLI[$POS]} ${GCC[$POS]} ${TELEGRAM[$POS]} ${ZFS[$POS]} \
    ${YOUTUBEDL[$POS]} ${ZATHURA[$POS]} ${ZATHURAPDF[$POS]} ${OVMF[$POS]} ${NMTUI[$POS]} ${QUTEBROWSER[$POS]}

  [ -x "$(command -v rpm-ostree)" ] && $SUDO rpm-ostree ex apply-live --allow-replacement
}
