#!/bin/bash

CONFIGURE_PACKAGES()
{
  NA=" "
  # DISTRO=(      Debian/Devuan             Fedora                AlmaLinux/Rocky/CentOS  Arch                Artix               Void                Alpine              OpenSuse                    FreeBSD               OpenBSD             )
  #---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------)
  ADBLOCK=(       "$NA"                     "$NA"                 "$NA"                   python-adblock      python-adblock      python3-adblock     py3-adblock         "$NA"                       py39-adblock          py3-adblock         )
  ANDROIDTOOLS=(  android-tools-adb         android-tools         "$NA"                   android-tools       "$NA"               android-tools       android-tools       "$NA"                       android-tools         "$NA"               )
  BTRFSPROGS=(    btrfs-progs               btrfs-progs           "$NA"                   btrfs-progs         btrfs-progs         btrfs-progs         btrfs-progs         btrfsprogs                  "$NA"                 "$NA"               )
  CRONTABS=(      python3-crontab           crontabs              crontabs                "$NA"               "$NA"               "$NA"               "$NA"               python3-crontab             py39-python-crontab   "$NA"               )
  DBUSX11=(       dbus-x11                  dbus-x11              dbus-x11                dbus                dbus                dbus-x11            dbus-x11            dbus-1-x11                  dbus                  dbus                )
  DOAS=(          "$NA"                     "$NA"                 "$NA"                   "$NA"               "$NA"               "$NA"               doas                "$NA"                       doas                  "$NA"               )
  DUNST=(         dunst                     dunst                 "$NA"                   dunst               dunst               dunst               dunst               dunst                       dunst                 dunst               )
  EMACSNX=(       emacs-nox                 emacs-nox             emacs-nox               emacs-nox           emacs-nox           emacs               emacs-nox           emacs-nox                   emacs-nox             emacs-nosx          )
  FEH=(           feh                       feh                   "$NA"                   feh                 feh                 feh                 feh                 feh                         feh                   feh                 )
  FFTHUMBNAILER=( ffmpegthumbnailer         ffmpegthumbnailer     "$NA"                   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer   ffmpegthumbnailer           ffmpegthumbnailer     ffmpegthumbnailer   )
  FIREFOX=(       firefox-esr               firefox               firefox                 firefox             firefox             firefox             firefox             MozillaFirefox              firefox-esr           firefox-esr         )
  FLATPAK=(       flatpak                   "$NA"                 flatpak                 flatpak             flatpak             flatpak             flatpak             flatpak                     "$NA"                 "$NA"               )
  FZF=(           fzf                       fzf                   "$NA"                   fzf                 fzf                 fzf                 fzf                 fzf                         fzf                   fzf                 )
  GCC=(           gcc                       "$NA"                 gcc                     gcc                 gcc                 "$NA"               gcc                 gcc                         gcc                   gcc%11              )
  GIFLIB=(        libgif-dev                "$NA"                 giflib-devel            giflib              giflib              giflib-devel        giflib-dev          giflib-devel                giflib                giflib              )
  GIT=(           git                       "$NA"                 git                     git                 git                 git                 git                 git                         git                   git                 )
  IMAGEMAGICK=(   imagemagick               ImageMagick           ImageMagick             imagemagick         imagemagick         ImageMagick         imagemagick         ImageMagick                 ImageMagick7-nox11    ImageMagick         )
  IMLIB2=(        libimlib2-dev             "$NA"                 imlib2-devel            imlib2              imlib2              imlib2-devel        imlib2-dev          imlib2-devel                imlib2                imlib2              )
  LF=(            "$NA"                     "$NA"                 "$NA"                   lf                  "$NA"               lf                  lf                  "$NA"                       lf                    lf                  )
  LIBEXIF=(       libexif-dev               "$NA"                 libexif-devel           libexif             libexif             libexif-devel       libexif-dev         libexif-devel               libexif               libexif             )
  LIBREOFFICE=(   libreoffice-calc          libreoffice-calc      libreoffice-calc        libreoffice-still   "$NA"               libreoffice-calc    "$NA"               libreoffice-calc            libreoffice           libreoffice         )
  LIBX11=(        libx11-dev                "$NA"                 libX11-devel            libx11              libx11              libX11-devel        libx11-dev          libX11-devel                libX11                "$NA"               )
  LIBXFT=(        libxft-dev                "$NA"                 libXft-devel            libxft              libxft              libXft-devel        libxft-dev          libXft-devel                libXft                "$NA"               )
  LIBXINERAMA=(   libxinerama-dev           "$NA"                 libXinerama-devel       libxinerama         libxinerama         libXinerama-devel   libxinerama-dev     libXinerama-devel           libXinerama           "$NA"               )
  LIBXRESDEV=(    libxres-dev               libXres-devel         libXres-devel           libxres             libxres             libXres-devel       libxres-dev         libXres-devel               libXres               "$NA"               )
  LIGHT=(         light                     light                 "$NA"                   light               "$NA"               light               light               "$NA"                       "$NA"                 "$NA"               )
  LMSENSORS=(     lm-sensors                lm_sensors            lm_sensors              lm_sensors          lm_sensors          lm_sensors          lm-sensors          sensors                     "$NA"                 "$NA"               )
  NFSUTILS=(      nfs-common                nfs-utils             nfs-utils               nfs-utils           nfs-utils           nfs-utils           nfs-utils           nfs-utils                   "$NA"                 "$NA"               )
  NMTUI=(         "$NA"                     NetworkManager-tui    NetworkManager-tui      "$NA"               "$NA"               "$NA"               networkmanager-tui  "$NA"                       "$NA"                 networkmanager-tui  )
  NTFS3G=(        ntfs-3g                   ntfs-3g               ntfs-3g                 ntfs-3g             ntfs-3g             ntfs-3g             ntfs-3g             ntfs-3g                     fusefs-ntfs           ntfs_3g             )
  OPENSSH=(       openssh-client            "$NA"                 openssh                 openssh             openssh             openssh             openssh             openssh                     "$NA"                 "$NA"               )
  OVMF=(          ovmf                      edk2-ovmf             edk2-ovmf               edk2-ovmf           edk2-ovmf           "$NA"               ovmf                ovmf                        "$NA"                 "$NA"               )
  PANDOCPDF=(     pandoc                    pandoc-pdf            pandoc-pdf              pandoc              pandoc              pandoc              "$NA"               pandoc                      "$NA"                 pandoc              )
  PICOM=(         picom                     picom                 "$NA"                   picom               picom               picom               picom               picom                       picom                 picom               )
  POPPLERUTILS=(  poppler-utils             poppler-utils         poppler                 poppler             poppler             poppler-utils       poppler-utils       poppler-tools               poppler-utils         poppler-utils       )
  PAUTILS=(       pulseaudio-utils          pulseaudio-utils      pulseaudio-utils        "$NA"               "$NA"               pulseaudio-utils    pulseaudio-utils    pulseaudio-utils            "$NA"                 pulseaudio          )
  PYTHON=(        "$NA"                     python3-devel         python3-devel           "$NA"               "$NA"               python3-devel       python3-dev         python3-devel               python311             python3             )
  PYTHON3PIP=(    python3-pip               "$NA"                 python-pip              python-pip          python-pip          python3-pip         py3-pip             python3-pip                 py39-pip              py3-pip             )
  PYTHON3SIX=(    python3-six               python3-six           python-six              python-six          python-six          python3-six         py3-six             python3-six                 py39-six              py3-six             )
  QEMU=(          qemu-system               "$NA"                 qemu-img                qemu-base           qemu-base           qemu                qemu-system-x86_64  qemu                        qemu                  qemu                )
  QUTEBROWSER=(   qutebrowser               qutebrowser           "$NA"                   qutebrowser         qutebrowser         qutebrowser         qutebrowser         qutebrowser                 qutebrowser           qutebrowser         )
  SCROT=(         scrot                     scrot                 "$NA"                   scrot               scrot               scrot               scrot               scrot                       scrot                 scrot               )
  SOX=(           sox                       sox                   sox                     sox                 sox                 sox                 sox                 sox                         sox                   sox                 )
  STOW=(          stow                      "$NA"                 stow                    stow                "$NA"               stow                stow                stow                        stow                  stow                )
  SWWW=(          "$NA"                     swww                  swww                    swww                swww                swww                swww                swww                        swww                  swww                )
  TELEGRAM=(      telegram-desktop          telegram-desktop      "$NA"                   telegram-desktop    "$NA"               telegram-desktop    telegram-desktop    telegram-desktop            telegram-desktop      "$NA"               )
  TIG=(           tig                       tig                   tig                     tig                 "$NA"               tig                 tig                 "$NA"                       tig                   tig                 )
  TRASHCLI=(      trash-cli                 trash-cli             "$NA"                   trash-cli           "$NA"               trash-cli           trash-cli           "$NA"                       "$NA"                 "$NA"               )
  UEBERZUG=(      "$NA"                     "$NA"                 "$NA"                   ueberzug            "$NA"               ueberzug            "$NA"               "$NA"                       py39-ueberzug         "$NA"               )
  UDISKIE=(       udiskie                   udiskie               "$NA"                   udiskie             udiskie             udiskie             udiskie             udiskie                     "$NA"                 "$NA"               )
  XDOTOOL=(       xdotool                   xdotool               xdotool                 xdotool             xdotool             xdotool             xdotool             xdotool                     xdotool               xdotool             )
  XF86INTEL=(     xserver-xorg-video-intel  xorg-x11-drv-intel    "$NA"                   xf86-video-intel    xf86-video-intel    xf86-video-intel    xf86-video-intel    xf86-video-intel            xf86-video-intel      "$NA"               )
  XINIT=(         xinit                     xorg-x11-xinit        xorg-x11-xinit          xorg-xinit          xorg-xinit          xinit               xinit               xinit                       xinit                 "$NA"               )
  XINPUT=(        xinput                    xinput                xinput                  xorg-xinput         xorg-xinput         xinput              xinput              xinput                      xinput                "$NA"               )
  XORGSERVER=(    xserver-xorg              xorg-x11-server-Xorg  xorg-x11-server-Xorg    xorg-server         xorg-server         xorg-minimal        xorg-server         xorg-x11-server             xorg-minimal          "$NA"               )
  XRANDR=(        x11-xserver-utils         xrandr                xrandr                  xorg-xrandr         xorg-xrandr         xrandr              xrandr              xrandr                      xrandr                "$NA"               )
  XRDB=(          x11-xserver-utils         xrdb                  xrdb                    xorg-xrdb           xorg-xrdb           xrdb                xrdb                xrdb                        xrdb                  "$NA"               )
  XSET=(          x11-xserver-utils         xset                  xset                    xorg-xset           xorg-xset           xset                xset                xset                        xset                  "$NA"               )
  YOUTUBEDL=(     yt-dlp                    youtube-dl            youtube-dl              youtube-dl          youtube-dl          youtube-dl          youtube-dl          youtube-dl                  youtube_dl            youtube-dl          )
  ZATHURA=(       zathura                   zathura               zathura                 zathura             zathura             zathura             zathura             zathura                     zathura               zathura             )
  ZATHURAPDF=(    zathura-pdf-poppler       zathura-pdf-poppler   zathura-pdf-poppler     zathura-pdf-poppler "$NA"               zathura-pdf-poppler zathura-pdf-poppler zathura-plugin-pdf-poppler  zathura-pdf-poppler   zathura-pdf-poppler )
  ZFS=(           zfsutils-linux            "$NA"                 "$NA"                   "zfs-utils"         "$NA"               zfs                 zfs                 "$NA"                       "$NA"                 "$NA"               )

  case "${RELEASE}" in
    "")                  echo "$RELEASE is not supported!"; exit 1 ;;
    Debian|Devuan)	        POS="0"
      MK="tux"
      PKGINSTALL="sudo apt-get -y install" ;;
    Fedora)                 POS="1"
      MK="tux"
      PKGINSTALL="sudo rpm-ostree install" ;;
    AlmaLinux|Rocky|CentOS) POS="2"
      MK="tux"
      PKGINSTALL="sudo dnf install -y" ;;
    Arch)                   POS="3"
      MK="tux"
      PKGINSTALL="sudo pacman --noconfirm -S" ;;
    Artix)                  POS="4"
      MK="tux"
      PKGINSTALL="sudo pacman --noconfirm -S" ;;
    Void)                   POS="5"
      MK="tux"
      PKGINSTALL="sudo xbps-install -Sy" ;;
    Alpine)                 POS="6"
      MK="tux"
      PKGINSTALL="doas apk add" ;;
    openSUSE)               POS="7"
      MK="tux"
      PKGINSTALL="sudo zypper install -y" ;;
    FreeBSD)                POS="8"
      MK="bsd"
      PKGINSTALL="doas pkg install -y" ;;
    OpenBSD)                POS="9"
      MK="bsd"
      PKGINSTALL="doas pkg_add -i" ;;
    NixOS)  MK="nixos" ;;
  esac

  if [ $RELEASE = Alpine ] || [ $RELEASE = FreeBSD ] || [ $RELEASE = OpenBSD ]; then
    SUDOAS="doas"
  else
    SUDOAS="sudo"
  fi

  if [ $RELEASE = Alpine ]; then
    mkdir -p /etc/doas.d
    DOASCONF="/etc/doas.d/doas.conf"
  else
    DOASCONF="/etc/doas.conf"
  fi

  if [ $RELEASE = Void ] || [ $RELEASE = Alpine ] || [ $RELEASE = FreeBSD ] || [ $RELEASE = OpenBSD ]; then
    $SUDOAS tee $DOASCONF << EOF
permit persist $USER as root
permit nopass $USER cmd reboot
permit nopass $USER cmd poweroff
permit nopass $USER cmd mount
permit nopass $USER cmd setleds
permit nopass $USER cmd zfs
permit nopass $USER cmd zpool
EOF
  fi

  if [ $RELEASE = NixOS ]; then
    $SUDOAS sed -i 's/#  vim/git/' /etc/nixos/configuration.nix
    $SUDOAS sed -i 's/#  wget/stow zfs/' /etc/nixos/configuration.nix

    $SUDOAS sed -i '$d' /etc/nixos/configuration.nix
    $SUDOAS tee -a /etc/nixos/configuration.nix << EOF
security.sudo.configFile = ''
  Defaults:$USER timestamp_timeout=60
'';
}
EOF

    $SUDOAS nixos-rebuild switch
  fi
}

INSTALL_PACKAGES()
{
  HYPRLAND="foot caja waybar ydotool tofi alacritty wl-clipboard grim slurp libnotify-bin ${SWWW}"

  DWM="i3lock xclip ${DBUSX11[$POS]} ${DUNST[$POS]} ${FEH[$POS]} ${GIFLIB[$POS]} ${LIBXFT[$POS]} ${IMLIB2[$POS]} ${LIBEXIF[$POS]} \
    ${LIBX11[$POS]} ${LIBXINERAMA[$POS]} ${PICOM[$POS]} ${PYTHON3PIP[$POS]} ${PYTHON3SIX[$POS]} ${SCROT[$POS]} ${SOX[$POS]} ${UEBERZUG[$POS]} \
    ${XDOTOOL[$POS]} ${XINPUT[$POS]} ${XORGSERVER[$POS]} ${XINIT[$POS]} ${XRANDR[$POS]} ${LIBXRESDEV[$POS]} ${XRDB[$POS]} ${XSET[$POS]}"

  $PKGINSTALL $HYPRLAND bzip2 ffmpeg groff keepassxc neovim mpv pipewire rsync sanoid syncthing unzip usbutils w3m wireguard-tools xdg-user-dirs zsh ripgrep \
    ${ADBLOCK[$POS]} ${ANDROIDTOOLS[$POS]} ${BTRFSPROGS[$POS]} ${CRONTABS[$POS]} ${FFTHUMBNAILER[$POS]} ${FIREFOX[$POS]} ${DOAS[$POS]} \
    ${FLATPAK[$POS]} ${FZF[$POS]} ${IMAGEMAGICK[$POS]} ${LIBREOFFICE[$POS]} ${LF[$POS]} ${NFSUTILS[$POS]} ${OPENSSH[$POS]} ${UDISKIE[$POS]} \
    ${LIGHT[$POS]} ${LMSENSORS[$POS]} ${NTFS3G[$POS]} ${PANDOCPDF[$POS]} ${POPPLERUTILS[$POS]} ${GIT[$POS]} ${XF86INTEL[$POS]} \
    ${PAUTILS[$POS]} ${PYTHON[$POS]} ${QEMU[$POS]} ${STOW[$POS]} ${TIG[$POS]} ${TRASHCLI[$POS]} ${GCC[$POS]} ${TELEGRAM[$POS]} ${ZFS[$POS]} \
    ${YOUTUBEDL[$POS]} ${ZATHURA[$POS]} ${ZATHURAPDF[$POS]} ${OVMF[$POS]} ${NMTUI[$POS]} ${QUTEBROWSER[$POS]}

  [ -x "$(command -v rpm-ostree)" ] && $SUDOAS rpm-ostree ex apply-live --allow-replacement
}
