#!/bin/bash

CONFIGURE_SYSTEM()
{
  $SUDOAS sed -i 's/GRUB_TIMEOUT=.*/GRUB_TIMEOUT=0/g' /etc/default/grub
  [ -d /boot/grub* ] && $SUDOAS "$(ls /usr/sbin | grep mkconfig)" -o /boot/"$(ls /boot | grep grub)"/grub.cfg
  echo "$USER" | $SUDOAS tee -a /etc/shutdown.allow
  echo "blacklist ideapad_laptop" | $SUDOAS tee /etc/modprobe.d/blacklist.conf

  if [ -z "$($SUDOAS dmesg | grep Hypervisor)" ]; then
    $SUDOAS mkdir /etc/X11/xorg.conf.d
    $SUDOAS tee /etc/X11/xorg.conf.d/20-intel.conf << EOF
Section "Device"
Identifier "Intel Graphics"
Driver "intel"
Option "TearFree" "true"
Option "DRI" "False"
EndSection
EOF

    $SUDOAS flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    $SUDOAS flatpak install com.github.qarmin.czkawka -y
    [ $RELEASE = "Alpine" ] && $SUDOAS flatpak install org.libreoffice.LibreOffice -y
  fi

  $SUDOAS mkdir -p /etc/polkit-1/rules.d/
  $SUDOAS tee /etc/polkit-1/rules.d/49-nopasswd_global.rules << EOF
/* Allow members of the wheel group to execute any actions
* without password authentication, similar to "sudo NOPASSWD:"
*/
polkit.addRule(function(action, subject) {
  if (subject.isInGroup("wheel")) {
    return polkit.Result.YES;
  }
});
EOF

  $SUDOAS usermod -s "$(which zsh)" $USER
  $SUDOAS mkdir -p /etc/modules-load.d
  echo zfs | $SUDOAS tee /etc/modules-load.d/zfs.conf

  [ ! -x "$(command -v ueberzug)" ] && git clone https://github.com/sorathpanzer/ueberzug.git
  [ ! -x "$(command -v ueberzug)" ] && pip install --user ./ueberzug
  [ -d ./ueberzug ] && $SUDOAS rm -R ueberzug

  [ -x "$(command -v sudo)" ] &&  echo "$USER ALL=(ALL) NOPASSWD: /usr/sbin/reboot,/usr/sbin/poweroff,/usr/bin/setleds" | $SUDOAS tee /etc/sudoers.d/$USER

  [ -x "$(command -v systemctl)" ] && $SUDOAS tee /etc/systemd/system/suspend@.service << EOF
[Unit]
Description=Lock X session using i3lock for user %i
Before=sleep.target
[Service]
User=%i
Type=forking
Environment=DISPLAY=:0
ExecStart=/usr/bin/xset dpms force suspend
ExecStartPre=/usr/bin/i3lock -c 000000
[Install]
WantedBy=sleep.target"
EOF

  [ -x "$(command -v systemctl)" ] && $SUDOAS mkdir -p /etc/systemd/system/getty@tty1.service.d/
  [ -x "$(command -v systemctl)" ] && $SUDOAS touch /etc/systemd/system/getty@tty1.service.d/override.conf
  [ -x "$(command -v systemctl)" ] && $SUDOAS tee /etc/systemd/system/getty@tty1.service.d/override.conf << EOF
[Service]
ExecStart=
ExecStart=-/usr/sbin/agetty --autologin $USER --noclear %I \$TERM
EOF
  [ -x "$(command -v systemctl)" ] && $SUDOAS systemctl enable suspend@$USER.service
  [ $RELEASE = Void ] && $SUDOAS xbps-remove -y sudo base-system
}
